# Generated by Django 5.1.7 on 2025-07-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hockey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=20),
        ),
    ]
