# Generated by Django 5.1.7 on 2025-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hockey', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttable',
            name='team_blue_indices',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='game_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='team',
            field=models.CharField(choices=[('K', 'Команда K (Красные)'), ('C', 'Команда C (Синие)')], max_length=1),
        ),
    ]
