# Generated by Django 5.1.7 on 2025-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hockey', '0003_tournamenttable_team_blue_indices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttable',
            name='schedule',
            field=models.JSONField(default=list),
        ),
    ]
